# Generated by Django 4.0.4 on 2022-07-22 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_competencia_pessoa_projeto_cadeira'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='linkPortfolio',
        ),
    ]
