# Generated by Django 4.0.4 on 2022-07-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_cadeira_professorauxiliar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadeira',
            name='topicos',
            field=models.CharField(max_length=300),
        ),
    ]
