# Generated by Django 4.0.4 on 2022-07-25 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_cadeira_topicos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competencia',
            old_name='competencia',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='cadeira',
            name='projetos',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='projeto',
        ),
        migrations.AddField(
            model_name='projeto',
            name='cadeira',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.cadeira'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='tecnologias',
            field=models.CharField(max_length=100),
        ),
    ]
