# Generated by Django 4.0.4 on 2022-07-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_rename_competencia_competencia_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='linkLinkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='linkLusofona',
            field=models.URLField(blank=True, null=True),
        ),
    ]
