# Generated by Django 4.0.4 on 2022-07-25 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_projeto_github_alter_projeto_linkyt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='participantes',
        ),
        migrations.AddField(
            model_name='projeto',
            name='participante1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p1', to='portfolio.pessoa'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='participante2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2', to='portfolio.pessoa'),
        ),
    ]
