# Generated by Django 4.0.6 on 2022-07-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_projeto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='nivel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
