# Generated by Django 4.0.6 on 2022-07-26 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_competencia_nivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_realizado', models.IntegerField()),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=500)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagem/')),
                ('relatorio', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('linkYt', models.URLField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluno', to='portfolio.pessoa')),
                ('orientador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orientador', to='portfolio.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=500)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagem/')),
                ('link', models.URLField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.pessoa')),
            ],
        ),
    ]
