# Generated by Django 4.0.6 on 2022-07-26 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_tfc_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfc',
            name='aluno2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aluno2', to='portfolio.pessoa'),
        ),
    ]
