# Generated by Django 4.0.6 on 2022-07-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_alter_noticia_autor_alter_noticia_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='autor',
        ),
        migrations.AlterField(
            model_name='blog',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
